framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            rabbitmq:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messages\adapters\JsonSerializer
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
             'App\Messages\message\IotMessage': rabbitmq
